### ISSUE TITLE
Type-building macros

### ISSUE THREAD

**Issue by dpomier** [EcsoKit/ecso#31]
Building macros are not properly processed: using `ecso` during a type building phase results in invalid executions.

Considering the following macro:
```haxe
import ecso.Entity;
import haxe.macro.Expr;

class Macro {
	public static function build():Array<Field> {
		var fields = [];
		final g = new EntityGroup();
		g.createEntity({ expected: true });
		g.foreachEntity(e -> {
			fields = (macro class T {
				public static final success = $v{e.expected};
			}).fields;
		});
		return fields;
	}
}
```
```haxe
@:build(Macro.build())
class Built {

}
```
The field `Built.success` shouldn't be missing once the macro has run.

**Comment by player-03** [comment]
I always specify `public static macro function build()`. Is `macro` optional and I just never knew?

What's the output if you print `fields` after `foreachEntity`?

**Comment by dpomier** [comment]
> Is `macro` optional [...] ?

It is indeed optional for type building macros, or more exactly "ignored" because AFAIK it is meant for function macros.

> What's the output if you print fields after foreachEntity?

It's an empty array, `foreachEntity` simply doesn't run.
